# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Blog"
  pre = "blogger"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "All posts"
  parent = "Blog"
  pageRef = "posts"
  weight = 20

# [[main]]
#   name = "Test sub menu"
#   parent = "Blog"
#   pageRef = "categories/test"
#   weight = 20

# [[main]]
#   name = "Test sub menu 2"
#   parent = "Blog"
#   pageRef = "categories/test"
#   weight = 30

# [[subnavigation]]
#   name = "unused topic"
#   pageRef = "tags/unused"
#   weight = 10
# [[subnavigation]]
#   name = "unused topic2"
#   pageRef = "tags/unused"
#   weight = 29
# [[subnavigation]]
#   name = "unused topic3"
#   pageRef = "tags/unused"
#   weight = 30

[[main]]
  name = "Tags"
  pre = "book_icon"
  pageRef = "tags"
  weight = 30

[[footer]]
  name = "X(Twitter)"
  pre = "x-twitter"
  url = "https://twitter.com/nyanyameowv"
  weight = 40

[[footer]]
  name = "Github"
  pre = "github"
  url = "https://github.com/alowhiter"
  weight = 50

[[footer]]
  name = "Itch.io"
  pre = "itch-io"
  url = "https://alowhiter.itch.io"
  weight = 60

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
